/*
 * This file is generated by jOOQ.
 */
package io.github.jinganix.admin.starter.helper.jooq.data;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/** A class modelling foreign key relationships and constraints of tables in the default schema. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {
  public static final UniqueKey<TestRecord> TEST_PK =
      Internal.createUniqueKey(
          TestTable.TEST, DSL.name("test_pk"), new TableField[] {TestTable.TEST.ID}, true);
}
