/*
 * This file is generated by jOOQ.
 */
package io.github.jinganix.admin.starter.helper.jooq.data;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TestRecord extends UpdatableRecordImpl<TestRecord> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>test.id</code>. */
  public void setId(Long value) {
    set(0, value);
  }

  /** Getter for <code>test.id</code>. */
  public Long getId() {
    return (Long) get(0);
  }

  /** Setter for <code>test.group_id</code>. */
  public void setGroupId(Long value) {
    set(1, value);
  }

  /** Getter for <code>test.group_id</code>. */
  public Long getGroupId() {
    return (Long) get(1);
  }

  /** Setter for <code>test.data</code>. */
  public void setData(String value) {
    set(2, value);
  }

  /** Getter for <code>test.data</code>. */
  public String getData() {
    return (String) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached TestRecord */
  public TestRecord() {
    super(TestTable.TEST);
  }
}
