name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 10 * * *' # Once per day at 10am UTC

jobs:
  commitlint:
    name: Check Commit Message
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: package.json
          failOnWarnings: true

  backend:
    name: Backend
    needs: [ commitlint ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 25 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}

      - name: Build backend
        run: ./gradlew clean build

      - name: Upload backend coverage to Coveralls
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: service/build/reports/jacoco/test/jacocoTestReport.xml
          format: jacoco
          flag-name: backend
          parallel: true
          base-path: service

  frontend:
    name: Frontend
    needs: [ commitlint ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Build frontend
        working-directory: frontend
        run: npm ci && npm run coverage && npm run build

      - name: Upload frontend coverage to Coveralls
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: frontend/coverage/lcov.info
          format: lcov
          flag-name: frontend
          parallel: true
          base-path: frontend

  coveralls:
    name: Coveralls
    needs: [ backend, frontend ]
    if: always() && needs.backend.result != 'cancelled' && needs.frontend.result != 'cancelled'
    runs-on: ubuntu-latest
    steps:
      - name: Finish Coveralls parallel build
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          carryforward: "backend,frontend"
