name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 10 * * *' # Once per day at 10am UTC

jobs:
  commitlint:
    name: Check Commit Message
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: package.json
          failOnWarnings: true

  backend:
    name: Backend
    needs: [ commitlint ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 25 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}

      - name: Build backend
        run: ./gradlew clean build

      - name: Upload backend coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: service/build/reports/jacoco/test/jacocoTestReport.xml
          flags: backend
          name: backend
          disable_search: true
          fail_ci_if_error: false

  frontend:
    name: Frontend
    needs: [ commitlint ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Build frontend
        working-directory: frontend
        run: npm ci && npm run coverage && npm run build

      - name: Upload frontend coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: frontend/coverage/lcov.info
          flags: frontend
          name: frontend
          disable_search: true
          fail_ci_if_error: false
