name: NETLIFY

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 21 ]
      fail-fast: false
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Setup JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        env:
          VITE_API_HOST: ${{ vars.VITE_API_HOST }}
        working-directory: frontend/admin
        run: npm install && npm run build

      - name: Deploy to Netlify
        working-directory: frontend/admin
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_API_TOKEN }} --dir=dist
